name: Bug Report
description: File a bug report
title: " Bug "
labels: ["bug", "critical"]
assignees:
  - EfrenRodriguez
body:
  - type: textarea
    id: overview
    attributes:
      label: Overview
      description: Provide description of the problem including actual behavior
      render: markdown
    validations:
      required: true
  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: Describe expected behavior, include requirements link and what specific requirement is being affected if applies.
      placeholder: "Expected behavior "
      value: "Expected behavior is: "
      render: markdown
    validations:
      required: true
  - type: dropdown
    id: software_image
    attributes:
      label: Software image
      description: In what software image you found the issue?
      options:
        - Consumer
        - Default
        - Reliability
        - Electronics
        - Custom (Add details in Software Version text box)
    validations:
      required: true
  - type: textarea
    id: software_details
    attributes:
      label: Software version
      description: Add specific details where the issue was found.
      render: markdown
      value: |
         - Application version / build where observed
         - Parametric version / build where observed
         - Configuration setup:
            - Personality
            - Cycle running
            - Options: `Add options selected such as spin, soil level, or any other relevant if it applies`
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      render: markdown
      placeholder: |
        1. First step
        2. Second step
        3. See error
    validations:
      required: true
  - type: textarea
    id: additional_information
    attributes:
      label: Additional information.
      description: Please add any additional information, include logs, images, etc.
      render: markdown
    validations:
      required: false
  - type: textarea
    id: root-cause
    attributes:
      label: Root cause
      description: Once solved, add the a brief root cause explanation for future reference on how this bug was closed
      render: markdown
    validations:
      required: false
  - type: textarea
    id: qa_section
    attributes:
      label: QA Section
      description: Details to test for QA
      render: markdown
      value: |
         - Build / hash to test:
         - Personality to test / hardware to test:
         - Parametric version and link:
    validations:
      required: false
